name: Receiver Pipe

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Sender Build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker *.cpp*
    
    - name: Receiver Build
      run:  g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o bmsReceiver Bms_Receiver/*.c*
        
    - name: Pipe
      run: |
         g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker *.cpp*
         g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o bmsReceiver Bms_Receiver/*.c*
         
    - name: bmsReceiver production
      run: ./bmsReceiver
