name: Send data using pipe

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker *.cpp
      
    - name: Build receiver for pipe
      run: gcc -DMAIN -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker1 ./Bms_Receiver/main.c
      
    - name: run
      run: ./testchecker
      
    - name : Sender | Reciever
      run: ./testchecker | gcc -DMAIN -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker1 ./Bms_Receiver/main.c
      
    - name: run
      run: ./testchecker1 
